config/routes.rb
Rails.application.routes.draw do
  get "/bookmark", to: "bookmarks#index", as: "bookmark"
  get "checked/:id", to: "bookmarks#checked", as: "checked"
  get "un_checked/:id", to: "bookmarks#un_checked", as: "un_checked"
  devise_for :users
  root "posts#index"
  resources :posts, param: :slug
  resources :not_found, only: :index
  resources :categories, param: :slug
  resources :tags, param: :slug
  resources :searches, only: :index
  resources :memos, only: [:create, :edit, :update, :destroy]
  get "*path", controller: "application", action: "render_404"
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  validates :user_id, presence: true
  validates :post_id, presence: true

  belongs_to :bookmark_users, class_name: "User", foreign_key: "user_id"
  belongs_to :bookmark_posts, class_name: "Post", foreign_key: "post_id"
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    if current_user && user_signed_in?
      @bookmark_posts = current_user.bookmark_posts.paginate(page: params[:page], per_page: Settings.page_posts_size).order(id: :desc)
    else
      redirect_to not_found_index_path
    end 
  end

  def checked
    @post = Post.find(params[:id])
    current_user.add_bookmark(@post)
    respond_to do |format|
        format.html { redirect_back(fallback_location: root_path) }
        format.js { render layout: false }
    end    
  end
  
  def un_checked
    @post = Post.find(params[:id])
    current_user.remove_bookmark(@post)
    respond_to do |format|
        format.html { redirect_back(fallback_location: root_path) }
        format.js { render layout: false }
    end
  end
end

app/views/bookmarks/_bookmark_icon.html.erb
<% if current_user %>
    <div class="bookmark_status">
        <% if current_user.bookmarked(post) %>
            <%= link_to un_checked_path(post.id) do %> 
                <span class="fa fa-star fa-lg star" tool-tip-toggle="tooltip-bookmark" data-original-title="ブックマーク削除"></span>
            <% end %>
        <% else %>
            <%= link_to checked_path(post.id) do %> 
                <span class="fa fa-star-o fa-lg star" tool-tip-toggle="tooltip-bookmark" data-original-title="ブックマーク追加"></span>
            <% end %>
        <% end %>
    </div>
<% end %>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script type="text/javascript">
$(document).ready(function(){
    $('[tool-tip-toggle="tooltip-bookmark"]').tooltip({
        placement : 'bottom'
    });
});
</script>

app/views/bookmarks/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1">
      <% @bookmark_posts.each do |post| %>
        <%= render "posts/post_item", post: post %>
      <% end %>
      <%= will_paginate @bookmark_posts, renderer: BootstrapPagination::Rails %>
    </div>
  </div>
</div>