config/routes.rb
Rails.application.routes.draw do
  get "/bookmark", to: "bookmarks#index", as: "bookmark"
  get "checked/:id", to: "bookmarks#checked", as: "checked"
  get "un_checked/:id", to: "bookmarks#un_checked", as: "un_checked"
  devise_for :users
  root "posts#index"
  resources :posts, param: :slug
  resources :not_found, only: :index
  resources :categories, param: :slug
  resources :tags, param: :slug
  resources :searches, only: :index
  resources :memos, only: [:create, :edit, :update, :destroy]
  get "*path", controller: "application", action: "render_404"
end

app/models/memo.rb
class Memo < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
    before_action :find_post, only: :create
    before_action :find_memo, only: [:edit, :update, :destroy]

    def create
        if !@post.memos.find_by user: current_user
            memo = Memo.new memo_params
            memo.user = current_user
            if memo.save
                @memo = @post.memos.find_by user: current_user
                respond_to do |format|
                    format.js
                end
            else
                flash[:danger] = t "memo_create.fail"
                redirect_to root_path
            end
        else
            flash[:danger] = t "memo_create.existed"
            redirect_to root_path
        end
    end

    def edit
        @post = @memo.post
        respond_to do |format|
            format.js
        end
    end

    def update
        if @memo.update_attributes memo_params
            @post = @memo.post
            respond_to do |format|
                format.js
            end
        else
            flash[:danger] = t "memo_update.fail"
            redirect_to root_path
        end
    end

    def destroy
        @post = @memo.post
        @memo.destroy
        @memo = current_user.memos.build
        respond_to do |format|
            format.js
        end
    end

    private
    def find_post
        return if @post = Post.find_by(id: params[:memo][:post_id])
        redirect_to not_found_index_path
    end

    def find_memo
        return if @memo = Memo.find_by(id: params[:id])
        redirect_to not_found_index_path
    end

    def memo_params
        params.require(:memo).permit :content, :post_id
    end
end

app/views/memos/_form.html.erb
<div class="field">
    <%= form_for memo, remote: true do |f| %>
        <%= f.hidden_field :post_id, value: post.id %>
        <% if !memo.new_record? %>
            <%= f.text_area :content, placeholder: "enter a memo and click enter...",
                class: "form-control title", rows: 10, value: memo.content%><br>
            <%= f.submit "Update Memo", class: "btn pmd-btn-flat pmd-ripple-effect btn-primary" %>
            <button type="button" class="btn pmd-btn-flat pmd-ripple-effect btn-default" onclick="cancel_update_memo()">Cancel</button>
        <% else %>
            <%= f.text_area :content, placeholder: "enter a memo and click enter...",
                class: "form-control title", rows: 10, value: ""%><br>
            <%= f.submit "Create Memo", class: "btn pmd-btn-flat pmd-ripple-effect btn-primary" %>
            <button type="button" class="btn pmd-btn-flat pmd-ripple-effect btn-default" onclick="cancel_create_memo()">Cancel</button>
        <% end %>
    <% end %>
</div><br>

app/views/memos/_show.html.erb
<h3>My memo</h3>
<hr><%= memo.content %>
<br><br>
<div class="pmd-card-actions">
    <%= link_to edit_memo_path(memo.id), remote: true do %>
        <button class="btn pmd-btn-flat pmd-ripple-effect btn-primary" type="button" id="edit-memo">Edit</button>
    <% end %>
    <%= link_to memo_path(memo.id), method: :delete, data: {confirm: "Are you sure?"}, remote: true do %>
        <button class="btn pmd-btn-flat pmd-ripple-effect btn-default" type="button" id="edit-memo">Delete</button>
    <% end %>
</div>

app/views/memos/create.js.erb
$("#memo-show").html("<%= escape_javascript(render("show", memo: @memo)) %>");
$("#memo-show").attr("class", "collapse.in");
$("#memo-form").attr("class", "collapse");
$("#memo-form").html("<%= escape_javascript(render("form", memo: @memo, post: @post)) %>");

app/views/memos/destroy.js.erb
$("#memo-form").html("<%= escape_javascript(render("form", memo: @memo, post: @post)) %>");
$("#memo-form").attr("class", "collapse");
$("#memo-show").attr("class", "collapse");
$("#create-memo-but").attr("class", "btn pmd-btn-flat pmd-ripple-effect btn-primary");

app/views/memos/edit.js.erb
$("#memo-form").html("<%= escape_javascript(render("form", memo: @memo, post: @post)) %>");
$("#memo-form").attr("class", "collapse.in");
$("#memo-show").attr("class", "collapse");

app/views/memos/update.js.erb
$("#memo-show").html("<%= escape_javascript(render("show", memo: @memo)) %>");
$("#memo-show").attr("class", "collapse.in");
$("#memo-form").attr("class", "collapse");
$("#memo-form").html("<%= escape_javascript(render("form", memo: @memo, post: @post)) %>");