config/routes.rb
Rails.application.routes.draw do
  get "/bookmark", to: "bookmarks#index", as: "bookmark"
  get "checked/:id", to: "bookmarks#checked", as: "checked"
  get "un_checked/:id", to: "bookmarks#un_checked", as: "un_checked"
  devise_for :users
  root "posts#index"
  resources :posts, param: :slug
  resources :not_found, only: :index
  resources :categories, param: :slug
  resources :tags, param: :slug
  resources :searches, only: :index
  resources :memos, only: [:create, :edit, :update, :destroy]
  get "*path", controller: "application", action: "render_404"
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <ul class="list-inline text-center">
          <li>
            <a href="https://twitter.com/">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
          <li>
            <a href="https://www.facebook.com/tattung.le.7">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
          <li>
            <a href="https://github.com/tunglt-0058/my_blog">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-github fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
        </ul>
        <p class="copyright text-muted">Copyright &copy;SBS Team Website 2020</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="site-heading">
          <h1><%= t "app_name" %></h1>
          <hr class="small">
          <span class="subheading">
            <%= t "app_slogan" %>
            <img width="70" height="70" src="<%= asset_path('sunbear.png') %>" />
          </span>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_nav.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-custom navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header page-scroll">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        Menu <i class="fa fa-bars"></i>
      </button>
      <a class="navbar-brand" href="/"><%= t("app_title") %></a>
    </div>
    <div class="navbar-header header-search col-md-5">
      <%= form_tag searches_path, method: :get, class: "form-search" do %>
        <span>
          <%= text_field_tag :search, params[:search], autocomplete: :off,
            placeholder: t("search"), class: "form-control posts-search",
            id: "posts-search" %>
        </span>
      <% end %>
      <span class="search-results">
        <ul class="results">
        </ul>
      </span>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= link_to "投稿", new_post_path %>
          </li>
          <li>
            <%= link_to "ブックマーク", bookmark_path %>
          </li>
          <li>
            <%= link_to "ログアウト", destroy_user_session_path,
                        method: :delete %>
          </li>
        <% else %>
          <% @categories.each do |category| %>
            <li>
              <%= link_to(category.name, category) %>
            </li>
          <% end %>
          <li>
            <a onclick="showModal()">ログイン</a>
          </li>
        <% end %>

      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>
<script>
    function showModal() {
        $('#form-login-modal').html('<%= j render "devise/sessions/form_modal" %>');
        $('#form-login-modal').modal('show');
    }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all",
                            "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application",
                               "data-turbolinks-track": "reload" %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Custom Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <%= render "layouts/header" %>
    <%= render "layouts/nav" %>
    <%= yield %>
    <div id="form-login-modal" class="modal fade" role="dialog">
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>